# Generated by Django 5.2.6 on 2025-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_confirmacion',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
