# Generated by Django 5.2.6 on 2025-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pedido_token_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('reembolso', 'Contra Reembolso'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
