# Generated by Django 5.2.6 on 2025-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
