# Generated by Django 5.2.6 on 2025-11-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cliente_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Entrega a domicilio'), ('tienda', 'Recoger en tienda')], default='domicilio', max_length=20),
        ),
    ]
