# Generated by Django 5.2.6 on 2025-11-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
    ]
