# Generated by Django 5.2.6 on 2025-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_producto_precio_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_minimo_gratis', models.DecimalField(decimal_places=2, default=50.0, help_text='Monto mínimo de compra para envío gratuito (€)', max_digits=10)),
                ('coste_envio_estandar', models.DecimalField(decimal_places=2, default=5.99, help_text='Coste del envío estándar (€)', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Envío',
                'verbose_name_plural': 'Configuración de Envío',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera_pago', 'En espera de pago'), ('confirmado', 'Confirmado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
