# Generated by Django 5.2.6 on 2025-11-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_configuracionenvio_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
    ]
