# Generated by Django 5.2.6 on 2025-11-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metodo_pago_favorito',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('reembolso', 'Contra reembolso')], default='tarjeta', max_length=20, null=True),
        ),
    ]
